baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'My New Hugo Site'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30

[[menus.main]]
identifier = 'about'
name = 'About'
url = '/about'
weight = 1

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"

[params]
  dateFormat = "2 January 2006"