name = 'tlzr'
license = 'GPL-3.0'
description = 'Minimal dark Hugo theme for thinkingbits.io'

homepage = 'https://github.com/jhleakakos/tlzr'
demosite = 'https://thinkingbits.io'

[author]
  name = 'Joseph Leakakos'
  homepage = 'https://thinkingbits.io'